# -*- coding: utf-8 -*-

"""
brainnapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from brainnapi.decorators import lazy_property
from brainnapi.configuration import Configuration
from brainnapi.configuration import Environment
from brainnapi.controllers.misc_controller import MiscController


class BrainnapiClient(object):

    @lazy_property
    def misc(self):
        return MiscController(self.config)

    def __init__(self, timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION,
                 basic_auth_user_name='TODO: Replace',
                 basic_auth_password='TODO: Replace', config=None):
        if config is None:
            self.config = Configuration(timeout=timeout,
                                        max_retries=max_retries,
                                        backoff_factor=backoff_factor,
                                        retry_statuses=retry_statuses,
                                        retry_methods=retry_methods,
                                        environment=environment,
                                        basic_auth_user_name=basic_auth_user_name,
                                        basic_auth_password=basic_auth_password)
        else:
            self.config = config
